### ISSUE TITLE
'can't modify frozen String' while creating policies

### ISSUE THREAD

**Issue by mmeuwese** [rabbitmq/chef-cookbook#429]
trying to create policies for a cluster using the policy_management recipe but getting the following error

```Recipe: rabbitmq::policy_management
==> rmq1:   * rabbitmq_policy[ha-mirror] action set
==> rmq1:     
==> rmq1:     ================================================================================
==> rmq1:     Error executing action `set` on resource 'rabbitmq_policy[ha-mirror]'
==> rmq1:     ================================================================================
==> rmq1:     
==> rmq1:     RuntimeError
==> rmq1:     ------------
==> rmq1:     can't modify frozen String
==> rmq1:     
==> rmq1:     Cookbook Trace:
==> rmq1:     ---------------
==> rmq1:     /var/chef/cache/cookbooks/rabbitmq/providers/policy.rb:30:in `policy_exists?'
==> rmq1:     /var/chef/cache/cookbooks/rabbitmq/providers/policy.rb:44:in `block in class_from_file'
==> rmq1:     
==> rmq1:     Resource Declaration:
==> rmq1:     ---------------------
==> rmq1:     # In /var/chef/cache/cookbooks/rabbitmq/recipes/policy_management.rb
==> rmq1:     
==> rmq1:      26:   rabbitmq_policy name do
==> rmq1:      27:     pattern policy['pattern']
==> rmq1:      28:     params policy['params']
==> rmq1:      29:     priority policy['priority']
==> rmq1:      30:     vhost policy['vhost']
==> rmq1:      31:     apply_to policy['apply_to']
==> rmq1:      32:     action :set
==> rmq1:      33:     notifies :restart, "service[#{node['rabbitmq']['service_name']}]"
==> rmq1:      34:   end
==> rmq1:      35: end
==> rmq1:     
==> rmq1:     Compiled Resource:
==> rmq1:     ------------------
==> rmq1:     # Declared in /var/chef/cache/cookbooks/rabbitmq/recipes/policy_management.rb:26:in `block in from_file'
==> rmq1:     
==> rmq1:     rabbitmq_policy("ha-mirror") do
==> rmq1:       params {"ha-mode"=>"all", "ha-sync-mode"=>"automatic"}
==> rmq1:       action [:set]
==> rmq1:       retries 0
==> rmq1:       retry_delay 2
==> rmq1:       default_guard_interpreter :default
==> rmq1:       declared_type :rabbitmq_policy
==> rmq1:       cookbook_name "rabbitmq"
==> rmq1:       recipe_name "policy_management"
==> rmq1:       pattern "."
==> rmq1:       priority 1
==> rmq1:       vhost "vhost"
==> rmq1:     end
==> rmq1:     
==> rmq1:     Platform:
==> rmq1:     ---------
==> rmq1:     x86_64-linux
==> rmq1:     
==> rmq1: [2017-04-04T13:45:47+00:00] INFO: Running queued delayed notifications before re-raising exception
==> rmq1: Running handlers:
==> rmq1: [2017-04-04T13:45:47+00:00] ERROR: Running exception handlers
==> rmq1: Running handlers complete
==> rmq1: [2017-04-04T13:45:47+00:00] ERROR: Exception handlers complete
==> rmq1: Chef Client failed. 0 resources updated in 09 seconds
==> rmq1: [2017-04-04T13:45:47+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> rmq1: [2017-04-04T13:45:47+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> rmq1: [2017-04-04T13:45:47+00:00] ERROR: rabbitmq_policy[ha-mirror] (rabbitmq::policy_management line 26) had an error: RuntimeError: can't modify frozen String
==> rmq1: [2017-04-04T13:45:48+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
also tried this with the same results

```rabbitmq_policy "ha-all" do
  pattern "^(?!amq\\.).*"
  params ({"ha-mode"=>"all"})
  priority 1
  action :set
end```

**Comment by michaelklishin** [comment]
See #422.
