### ISSUE TITLE
Incompatible erlang version with latest rabbitmq build

### ISSUE THREAD

**Issue by pauldmccann** [rabbitmq/chef-cookbook#478]
This cookbook uses the erlang cookbook to add the erlang prerequisite.  However, using that cookbook with the EPEL repository only allows version R16 of erlang.  I was able to use the esl-erlang package to get to erlang 20.2, but the rabbitmq package didn't recognize that as an acceptable version of erlang.  

For my needs, I modified the cookbook to use the zero dependency erlang package from rmq (https://github.com/rabbitmq/erlang-rpm), but I'm not sure if that's the best solution.   It seems the real issue is that the rabbitmq 3.7.3 package didn't recognize 20.2.2 esl-erlang as an acceptable version.

**Comment by michaelklishin** [comment]
Depending on an Erlang cookbook that provisions 19.3 or a later version should be good enough. EPEL, esl-erlang and all that will have to go in favor of the zero dependency RabbitMQ RPM. Please submit a PR with your changes and we'll consider it.

**Comment by isuftin** [comment]
FYI hitting the same issue on CentOS 7:

```
       * rpm_package[/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm] action install

           ================================================================================
           Error executing action `install` on resource 'rpm_package[/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of ["rpm", "-i", "/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm"] ----
           STDOUT:
           STDERR: warning: /tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 6026dfca: NOKEY
           error: Failed dependencies:
                erlang >= 19.3 is needed by rabbitmq-server-3.7.3-1.el7.noarch
           ---- End output of ["rpm", "-i", "/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm"] ----
           Ran ["rpm", "-i", "/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm"] returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/default.rb

           161:     rpm_package "#{Chef::Config[:file_cache_path]}/#{rpm_package_name}"
           162:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/default.rb:161:in `from_file'

           rpm_package("/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm") do
             package_name "/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm"
             action [:install]                                                                                                                                                                      default_guard_interpreter :default
             declared_type :rpm_package
             cookbook_name "rabbitmq"
             recipe_name "default"
             source "/tmp/kitchen/cache/rabbitmq-server-3.7.3-1.el7.noarch.rpm"
             version "3.7.3-1.el7"
           end

           System Info:
           ------------
           chef_version=13.7.16
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-client worker: ppid=4858;start=18:10:12;
           executable=/opt/chef/bin/chef-client
```

**Comment by isuftin** [comment]
My current workaround for this is to have the following attributes set for my node:
```
default['erlang']['install_method'] = 'esl'
default['erlang']['esl']['version'] = '19.3.6-1'
```

This works for CentOS 7 (and would probably also work for CentOS 6). Note that if you have a previous version of Erlang installed, this might break spectacularly during the rabbitmq::default run:

```
       Recipe: erlang::esl                                                                                                                                                  [329/45430]
         * yum_package[esl-erlang] action install

           ================================================================================
           Error executing action `install` on resource 'yum_package[esl-erlang]'
           ================================================================================

           Chef::Exceptions::Exec
           ----------------------
           yum -d0 -e0 -y install esl-erlang-19.3.6-1 returned 1:
           STDOUT:
           STDERR:

           Transaction check error:
             file /usr/bin/epmd from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
             file /usr/bin/erl from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
             file /usr/bin/erlc from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
             file /usr/bin/escript from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
             file /usr/bin/run_erl from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
             file /usr/bin/to_erl from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
             file /usr/bin/ct_run from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-common_test-R16B-03.18.el7.x86_64
             file /usr/bin/dialyzer from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-dialyzer-R16B-03.18.el7.x86_64
             file /usr/bin/typer from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-typer-R16B-03.18.el7.x86_64

           Error Summary
           -------------


           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/erlang/recipes/esl.rb

            45:   package 'esl-erlang' do
            46:     version node['erlang']['esl']['version'] if node['erlang']['esl']['version']
            47:   end
            48: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/erlang/recipes/esl.rb:45:in `from_file'

           yum_package("esl-erlang") do
             package_name "esl-erlang"
             action [:install]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "erlang"
             recipe_name "esl"
             version "19.3.6-1"
           end

           System Info:
           ------------
           chef_version=13.7.16
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-client worker: ppid=5634;start=18:19:17;
           executable=/opt/chef/bin/chef-client


       Running handlers:
       [2018-02-14T18:19:38+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-02-14T18:19:38+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 20 seconds
       [2018-02-14T18:19:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-02-14T18:19:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-02-14T18:19:38+00:00] ERROR: yum_package[esl-erlang] (erlang::esl line 45) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install esl-erlang-19.3.6-1 returned 1:
       STDOUT:
       STDERR:

       Transaction check error:
         file /usr/bin/epmd from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
         file /usr/bin/erl from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
         file /usr/bin/erlc from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
         file /usr/bin/escript from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
         file /usr/bin/run_erl from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
         file /usr/bin/to_erl from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-erts-R16B-03.18.el7.x86_64
         file /usr/bin/ct_run from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-common_test-R16B-03.18.el7.x86_64
         file /usr/bin/dialyzer from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-dialyzer-R16B-03.18.el7.x86_64
         file /usr/bin/typer from install of esl-erlang-19.3.6-1.x86_64 conflicts with file from package erlang-typer-R16B-03.18.el7.x86_64

       Error Summary
       -------------


       [2018-02-14T18:19:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-cluster-1-centos-7>.  Please see .kitchen/logs/default-cluster-1-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by michaelklishin** [comment]
At least partially this should be addressed in the Erlang cookbook. Depending on a legacy repository is not a good idea.

We will likely force RabbitMQ team's zero dependency Erlang RPM in this cookbook in the future.

**Comment by isuftin** [comment]
@michaelklishin Is the ESL Erlang repo is legacy? Is there a better workaround for this than what I am doing for the time being?

**Comment by michaelklishin** [comment]
I added a [doc section](https://github.com/rabbitmq/chef-cookbook#37x) that explains how to provision Erlang 19.3.6 or later using the current release of the Erlang cookbook.

**Comment by michaelklishin** [comment]
The ESL repo is not "legacy", in fact, some very recent Ubuntu and Debian versions only provide 19.2 at best, so ESL repo *must* be used (and we're lucky that the Erlang cookbook supports it).
