### ISSUE TITLE
Confusion over how to set cluster attributes correctly in Test Kitchen

### ISSUE THREAD

**Issue by isuftin** [rabbitmq/chef-cookbook#482]
My test kitchen snippet, using latest 5.5.0 cookbook:

```
---
driver:
  name: vagrant
  provision: true

provisioner:
  product_name: chef

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default-cluster-seed
    data_bags_path: 'test/integration/default/data_bags/'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[rabbitmq]
      - recipe[rabbitmq]
      - recipe[rabbitmq::plugin_management]
      - recipe[rabbitmq::cluster]
      - recipe[rabbitmq::mgmt_console]
    attributes: {
      "rabbitmq" : {
        "version" : "3.7.3",
        "rpm_package_url" : "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.3/",
        "enabled_plugins" : [],
        "disabled_plugins" : [],
        "enabled_users" : [
          {
            "name" : "admin",
            "password" : "adminadmin",
            "tag" : "administrator",
            "rights" : [
              {
                "conf" : ".*",
                "write" : ".*",
                "read" : ".*"
              }
            ]
          }
        ],
        "disabled_users" : [ "guest" ],
        "clustering" : {
            "enable" : true,
            "erlang_cookie" : "AnyAlphaNumericStringWillDo",
            "use_auto_clustering" : true,
            "cluster_name" : "",
            "cluster_nodes" : [ { "name" : "rabbit@rabbit.seed.local", "type" : "disc" } ]
        }
      },
      "erlang" : {
          "install_method" : "esl",
          "esl" : {
            "version" : "19.3.6-1"
            }
      }
    }
    driver:
      vm_hostname: rabbit.seed.local
      network:
      - ["private_network", {ip: "192.168.33.35"}]
      - ["forwarded_port", {guest: 5672, host: 5672, auto_correct: true}] # RabbitMQ
      - ["forwarded_port", {guest: 15672, host: 15672, auto_correct: true}] # RabbitMQ
```

With the above, I try to perform a Kitchen converge, here is the error I am seeing:

```
       Recipe: rabbitmq::cluster
         * rabbitmq_cluster[[]] action set_cluster_name (up to date)
         * rabbitmq_cluster[[]] action change_cluster_node_type

           ================================================================================
           Error executing action `change_cluster_node_type` on resource 'rabbitmq_cluster[[]]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `[]' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/rabbitmq/providers/cluster.rb:259:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/cluster.rb

            41: rabbitmq_cluster static_cluster_nodes do
            42:   cluster_name node['rabbitmq']['clustering']['cluster_name']
            43:   action [:set_cluster_name, :change_cluster_node_type]
            44: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/cluster.rb:41:in `from_file'

           rabbitmq_cluster("[]") do
             action [:set_cluster_name, :change_cluster_node_type]
             default_guard_interpreter :default
             declared_type :rabbitmq_cluster
             cookbook_name "rabbitmq"
             recipe_name "cluster"
             cluster_name ""
             cluster_nodes "[]"
           end

           System Info:
           ------------
           chef_version=13.7.16
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-client worker: ppid=4241;start=22:38:29;
           executable=/opt/chef/bin/chef-client

       Recipe: rabbitmq::default
         * service[rabbitmq-server] action restart
           - restart service service[rabbitmq-server]

       Running handlers:
       [2018-02-14T22:42:33+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-02-14T22:42:33+00:00] ERROR: Exception handlers complete
       Chef Client failed. 34 resources updated in 04 minutes 03 seconds
       [2018-02-14T22:42:33+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-02-14T22:42:33+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-02-14T22:42:33+00:00] ERROR: rabbitmq_cluster[[]] (rabbitmq::cluster line 41) had an error: NoMethodError: undefined method `[]' for nil:NilClass
       [2018-02-14T22:42:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-cluster-seed-centos-7>.  Please see .kitchen/logs/default-cluster-seed-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Am I doing something wrong on my end?

**Comment by isuftin** [comment]
And here I have some very odd behavior when I am troubleshooting...

Before anything else, I try to add a default recipe into my wrapper cookbook. This gets run first before anything else. I add one line to it:

`puts node['rabbitmq']['clustering'].to_json`

And during the kitchen run I see:
```
...
       Compiling Cookbooks...
       {"enable":true,"erlang_cookie":"AnyAlphaNumericStringWillDo","use_auto_clustering":true,"cluster_name":"","cluster_nodes":[],"cluster_partition_handling":"ignore","node_type":"
master","master_node_name":"rabbit@rabbit1","cluster_node_type":"disc"}
...
```

Ok, I then update my recipe to look like:
```
puts node['rabbitmq']['clustering']
puts node['rabbitmq']['clustering'].to_json
```

Now I see...
```
Compiling Cookbooks...
       {"enable"=>true, "erlang_cookie"=>"AnyAlphaNumericStringWillDo", "use_auto_clustering"=>true, "cluster_name"=>"", "cluster_nodes"=>[{"name"=>"rabbit@rabbit.seed.local", "type"=>"disc"}], "cluster_partition_handling"=>"ignore", "node_type"=>"master", "master_node_name"=>"rabbit@rabbit1", "cluster_node_type"=>"disc"}
```

And now the error in the cookbook changes:
```
       Recipe: rabbitmq::cluster
         * rabbitmq_cluster[[{"name":"rabbit@rabbit.seed.local","type":"disc"}]] action set_cluster_name (up to date)
         * rabbitmq_cluster[[{"name":"rabbit@rabbit.seed.local","type":"disc"}]] action change_cluster_node_type

           ================================================================================
           Error executing action `change_cluster_node_type` on resource 'rabbitmq_cluster[[{"name":"rabbit@rabbit.seed.local","type":"disc"}]]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `[]' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/rabbitmq/providers/cluster.rb:259:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/cluster.rb

            41: rabbitmq_cluster static_cluster_nodes do
            42:   cluster_name node['rabbitmq']['clustering']['cluster_name']
            43:   action [:set_cluster_name, :change_cluster_node_type]
            44: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/rabbitmq/recipes/cluster.rb:41:in `from_file'

           rabbitmq_cluster("[{"name":"rabbit@rabbit.seed.local","type":"disc"}]") do
             action [:set_cluster_name, :change_cluster_node_type]                                                                                                                                  default_guard_interpreter :default
             declared_type :rabbitmq_cluster
             cookbook_name "rabbitmq"
             recipe_name "cluster"
             cluster_name ""
             cluster_nodes "[{\"name\":\"rabbit@rabbit.seed.local\",\"type\":\"disc\"}]"
           end

           System Info:
           ------------
           chef_version=13.7.16
          platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-client worker: ppid=17674;start=23:01:10;
           executable=/opt/chef/bin/chef-client


       Running handlers:
       [2018-02-14T23:01:41+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-02-14T23:01:41+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 31 seconds
       [2018-02-14T23:01:41+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-02-14T23:01:41+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-02-14T23:01:41+00:00] ERROR: rabbitmq_cluster[[{"name":"rabbit@rabbit.seed.local","type":"disc"}]] (rabbitmq::cluster line 41) had an error: NoMethodError: undefined method `[]' for nil:NilClass
       [2018-02-14T23:01:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-cluster-seed-centos-7>.  Please see .kitchen/logs/default-cluster-seed-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We do not have access to your wrapper cookbook. Somehow one of the `cluster_nodes` is a `nil`. I changed line 259 to be more defensive in https://github.com/rabbitmq/chef-cookbook/commit/9e429caf021f8ed05bce1f6d5c0f4b55661ae710 but it's merely a workaround.

That line has changed recently in #477. I don't see how that change would matter since the previous version was a) Wrong, b) Didn't handle `nil` nodes either.

**Comment by michaelklishin** [comment]
I do have some thoughts. They are:

 * Team RabbitMQ does not use GitHub issues
 * For better or worse, we maintain this cookbook now, so the rule above applies to it just like it does to our other repos
 * Consider enabling debug logging and diving instead of waiting for strangers on the Internet to share their guess.es When you are done, feel free to file a specific issue with details, steps to reproduce and your findings, which will not be directed to the mailing list because it actionable.

**Comment by isuftin** [comment]
Answer: Adding attribute `default['rabbitmq']['additional_env_settings']  = ["RABBITMQ_USE_LONGNAME=true"]`

My node name had dots in it (rabbit.seed.local) and the node name created by RabbitMQ was just `rabbit`. The value coming in [here](https://github.com/rabbitmq/chef-cookbook/blob/master/providers/cluster.rb#L257) is just `rabbit` and of course the name in my cluster_nodes is not that. Hence, nil. That's a tricky thing to figure out. Perhaps add some documentation around that. Once I get actual multi-machine clustering working properly in test kitchen I'll drop my kitchen yaml off here.

**Comment by isuftin** [comment]
Unfortunately this is not something that will work easily in Test Kitchen without a higher level DNS resolver. 

The problem is that Test Kitchen fires up individual VMs via Vagrant (by default) and the VMs do not know about each other's hostnames. This works if after firing up the VMs I manually go in and add the hostnames of the other hosts to each one and re-converge.

I've tried vagrant-hostmanager and vagrant-hosts but neither seem to fit the bill. The other option is looking into various Chef-based cookbooks that alter /etc/hosts and run those first.

**Comment by isuftin** [comment]
FYI the hash issue I think is a Chef client bug - https://github.com/chef/chef/issues/6792

That's why my suggestion here happens to be a weak workaround to it: https://github.com/rabbitmq/chef-cookbook/issues/482#issuecomment-365778270
