### ISSUE TITLE
Cloning resource attributes for rabbitmq_user

### ISSUE THREAD

**Issue by Wing924** [rabbitmq/chef-cookbook#491]
When I `include_recipe 'rabbitmq::user_management'`, I got those warning message.
```
 Deprecated features used!
         Cloning resource attributes for rabbitmq_user[guest] from prior resource
       Previous rabbitmq_user[guest]: /var/tmp/kitchen/cache/cookbooks/rabbitmq/recipes/user_management.rb:27:in `block in from_file'
       Current  rabbitmq_user[guest]: /var/tmp/kitchen/cache/cookbooks/rabbitmq/recipes/user_management.rb:31:in `block in from_file' at 1 location:
           - /var/tmp/kitchen/cache/cookbooks/rabbitmq/recipes/user_management.rb:31:in `block in from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
         Cloning resource attributes for rabbitmq_user[guest] from prior resource
       Previous rabbitmq_user[guest]: /var/tmp/kitchen/cache/cookbooks/rabbitmq/recipes/user_management.rb:31:in `block in from_file'
       Current  rabbitmq_user[guest]: /var/tmp/kitchen/cache/cookbooks/rabbitmq/recipes/user_management.rb:36:in `block (2 levels) in from_file' at 1 location:
           - /var/tmp/kitchen/cache/cookbooks/rabbitmq/recipes/user_management.rb:36:in `block (2 levels) in from_file'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```

This is because `rabbitmq_user` use same name.
https://github.com/rabbitmq/chef-cookbook/blob/v5.x/recipes/user_management.rb#L27

We can make the name unique to avoid this problem.

**Comment by devsibwarra** [comment]
Pretty sure the first response from @jjasghar and @michaelklishin would be that PRs are welcome.  :)

Changes to `user_management.rb` should be pretty easy and would look similar to
```
- rabbitmq_user user['name'] do
+ rabbitmq_user "do-action-for-#{user['name']}" do
+   user user['name']
```

If you don't want to make a PR to fix this, I can do it later this week

**Comment by jjasghar** [comment]
@devsibwarra couldn't have said it better myself. :)

**Comment by michaelklishin** [comment]
@devsibwarra thank you, that would be appreciated.
